### ISSUE TITLE
Similarity Algorithms

### ISSUE THREAD

**Issue by elfnursenturk** [CankayaUniversity/ceng-407-408-2023-2024-FOODMAX-WASTEMIN-Food-loss-waste-prevention-and-Donation-Platform#15]
-Using different similarity algorithms for recommendation system.

**Comment by FeyzaAy** [comment]
We tried fussy algorithm, euclidian distance and cosine similarity algorithm, and we decided that cosine similarity is better than others.

**Comment by elfnursenturk** [comment]
is solved.
